apps/meeting/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    
    #Meeting
    path('register/',RegisterMeeting.as_view(), name='register'), 
	path('visualize/', watchMeeting.as_view(), name='visualize'),
	path('visualize/register_comment/<int:pk>/<int:id_idea>/', registerComment, name='register_comment'),
    path('detail_meeting/<int:id_reu>/comments_list/<int:id_idea>/', comments_list, name = 'comments_list'),
    path('visualize/detail_meeting/<int:pk>/', detailMeeting, name='detail_meeting'),
    path('visualize/detail_meeting/upload/<int:pk>/',BasicUploadView, name='upload'),
    path('visualize/detail_meeting/close_meeting/<int:pk>/',closeMeeting, name='close'),
    path('buscar_idea/', IdeaAjaxMeeting.as_view(), name='buscar_idea'),
    path('buscar_usuario/', UserAjaxMeeting.as_view(), name='buscar_usuario'),
    path('update/<int:id>', UpdateMeeting, name='update'),

	#Generar pdf
	path('ticket/<int:pk>/', MeetingGeneratorPdf.as_view(), name='ticket'),

]

verne2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from apps.idea.views import visualizeDashboardUser
from django.views.generic import TemplateView
from apps.home.views import *


#Modulos del API
from rest_framework import routers
from apps.idea.api.api_rest import UserViewSet,IdeaViewSet,PhaseViewSet
from apps.meeting.api.api_rest import MeetingViewSet,UserVotesgViewSet
from apps.activity.api.api_rest import ActivityViewSet
from apps.prize.api.api_rest import PrizeViewSet,ActionViewSet,LeguasViewSet
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Documentación API')
router = routers.DefaultRouter()
router.register(r'usuario', UserViewSet, basename='usuario')
router.register(r'idea', IdeaViewSet, basename='idea')
router.register(r'reunion', MeetingViewSet, basename='reunion')
router.register(r'votacion', UserVotesgViewSet, basename='votacion')
router.register(r'actividad', ActivityViewSet, basename='actividad')
router.register(r'premios', PrizeViewSet, basename='premios')
router.register(r'acciones', ActionViewSet, basename='acciones')
router.register(r'leguas', LeguasViewSet, basename='leguas')
router.register(r'fases', PhaseViewSet, basename='fases')


urlpatterns = [
	path('admin/', admin.site.urls, name = 'admin_django'),

	#API
    path('api/v1/', include(router.urls)),
    path(r'documentacion/', schema_view), #Documentación Principal 

    #Autenticación Google
    #path('accounts/', include('allauth.urls')), # new

	#Autenticación Google
    path("login", login_request, name="login"),
    path("logout", logout_request, name= "logout"),
    path('microsoft/', include('microsoft_auth.urls', namespace='microsoft')),
	#Llamado a las apps para crear la ruta
	path('ideas/',include(('apps.idea.urls','idea'))),
	path('meeting/',include(('apps.meeting.urls','meeting'))),
	path('prize/',include(('apps.prize.urls','prize'))),
	path('activity/',include(('apps.activity.urls','activity'))),
	path('dashboard/', visualizeDashboardUser, name='dashboard'),
	path('users/',include(('apps.users.urls','users'))),
	path('indicador/',include(('apps.indicators.urls','indicator'))),

	#URL Landing Page
	path('', ViewHome, name='home'),
	path('sign_in', LoginPage, name='singin'),

    #Manejo de errores
	path('404/', TemplateView.as_view(template_name="404.html")),
    path('500/', TemplateView.as_view(template_name="500.html")),
    path('403/', TemplateView.as_view(template_name="403.html")),
  	path('ckeditor/', include('ckeditor_uploader.urls')),

]
 

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	import debug_toolbar
	urlpatterns = [
		path('__debug__/', include(debug_toolbar.urls)),
	] + urlpatterns    

admin.site.site_header = "Administrador de Verne 2.0"
admin.site.site_title = "Administración de Verne 2.0"
admin.site.index_title = "Administración de Verne 2.0"

apps/meeting/models.py
from email.policy import default
from django.db import models
from simple_history.models import HistoricalRecords
from apps.idea.models import Idea
from django.contrib.auth.models import User
from django.db.models.fields import URLField
from ckeditor_uploader.fields import  RichTextUploadingField



class Meeting(models.Model):
	name=models.CharField(max_length=50,verbose_name=u'Nombre Reunión')
	date=models.DateField(null=True,verbose_name=u'Fecha de creación')
	document_act=models.FileField(upload_to='document_meeting/', blank=True,null=True)
	place=models.CharField(max_length=50,verbose_name=u'Lugar')
	start_time=models.TimeField(null=True,verbose_name=u'Hora de Inicio')
	end_time=models.TimeField(null=True,verbose_name=u'Hora Fin')
	is_active=models.BooleanField(max_length=100, default=True, verbose_name=u'Está calificada')
	link_documentation=URLField(max_length=1500, verbose_name=u'Enlace a Documentación', null = True, blank=True, default="https://drive.google.com/")
	id_idea=models.ManyToManyField(Idea)
	user_comitte=models.ManyToManyField(User)
	history = HistoricalRecords()

	class Meta:
		verbose_name = "Reunión Comité"
		verbose_name_plural = "Reuniones Comité"

	def __str__(self):
		return self.name

class UserVotes(models.Model):
	STATE_PHASE=(
     
	("1","Avanza de fase"),
	("2","Se mantiene en fase"),
  	("3","Ideas en Stand By"), )
	STATE_PRIORITY=(
     
	("1","Sube de prioridad"),
 	("2","Baja de prioridad"),
    ("3","Se mantiene en prioridad"))
	
	vote=models.CharField(max_length=100, choices=STATE_PHASE,verbose_name=u'Voto de Fase')
	vote_priority=models.CharField(max_length=100, choices=STATE_PRIORITY,verbose_name=u'Voto de Prioridad')
	id_meeting=models.ForeignKey(Meeting,on_delete=models.SET_NULL,null = True)
	id_idea=models.ForeignKey(Idea,on_delete = models.SET_NULL,null = True, verbose_name=u'Miembro Comité',)
	id_user_comitte=models.ForeignKey(User,on_delete = models.SET_NULL,null = True)	
	is_evaluate=models.BooleanField(default=False,verbose_name=u'Está calificada')
	phase_actual=models.IntegerField(null=True,blank=True)
	message = models.CharField(max_length=500,verbose_name=u'Comentario' ,null=True,blank=True, default="Sin comentarios")
	pub_date=models.DateTimeField('date_published',auto_now=True)
	history = HistoricalRecords()
	def __str__(self):
		return "message: {0}".format(self.vote) 

	class Meta:
		verbose_name = "Voto Comité"
		verbose_name_plural = "Votos Comité"

apps/meeting/views.py
from cProfile import Profile
from re import template
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required,permission_required
from django.views.generic import ListView, CreateView,View
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import *
from apps.idea.models import Idea,Phase_Date
from .forms import *
from apps.idea.views import SearchAjaxIdea,SearchUserAjax,_FormValid
from django.urls import reverse_lazy
from django.conf import settings
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.core.exceptions import ObjectDoesNotExist
from django.template.loader import get_template
from weasyprint import CSS, HTML
from django.http.response import HttpResponse
import os
from django.contrib.auth.mixins import PermissionRequiredMixin
from apps.users.models import Profile

# ----------------------------------------------------------------------------------
""" Creación de reunión: El administrador agenda la reuníón y al enviar los datos del formulario
automáticamente , se guarda en la tabla intermedia UserVotes"""

class RegisterMeeting(_FormValid,CreateView,PermissionRequiredMixin):
    
	model = Idea
	permission_required = 'meeting.add_meeting'
	form_class = RegisterMeetingForm
	template_name= 'meeting/register_meeting.html'
	sucess_url = reverse_lazy('meeting:visualize')
	success_message = '¡La reunión fue creada correctamente!'
	error_message = 'No se guardo con exito.'

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		form_header = dict(request.POST.lists())

		if 'user_comitte' in form_header:
			user_comitte_query = User.objects.filter(pk__in=form_header['user_comitte'])  #[1,2,3]
			form.fields['user_comitte'].queryset = user_comitte_query

		email_list = user_comitte_query.values('email')
		lista_nueva = []
		
		for lista in email_list:
			lista_nueva.append(lista['email'])

		host_email = [settings.EMAIL_HOST_USER]
		lista_nueva.extend(host_email)

		if form.is_valid():
			users_invited = form.cleaned_data['user_comitte']
			metting_save = form.save()
			idea_query = Idea.objects.filter(meeting__id=metting_save.pk )
			for user in users_invited:
				user_comite = user.id
				for idea in idea_query:
					UserVotes.objects.create(
						id_meeting_id = metting_save.pk,
						id_idea_id = int(idea.id), 
						id_user_comitte_id = int(user_comite),)

			try:
			    
				body = render_to_string(
					'emails/nueva_reunion.html', {
					   	'name': request.POST.get('name'),
						'date': request.POST.get('date'),
						'place': request.POST.get('place'),
      					'start_time': request.POST.get('start_time'),
           				'end_time': request.POST.get('end_time'),	},)
				email_message = EmailMessage(
					subject='¡Tienes una nueva reunión en Verne!',
					body=body,
					from_email=host_email,
					to=lista_nueva,
					)
				email_message.content_subtype = 'html'
				email_message.send()
			except ObjectDoesNotExist as e:
				error = e
			return self.form_valid(form)
		else:

			self.form_invalid(form)
		return redirect(str(self.success_url))


# Clases que heredan de la app de Idea para los campos con AJAX ----------------------------------------

class UserAjaxMeeting(SearchUserAjax):
	pass

class IdeaAjaxMeeting(SearchAjaxIdea):
	pass

# Editar Reunión-----------------------------------------------------------------------------------------

@login_required()
@permission_required('meeting.add_meeting', raise_exception=True)

def UpdateMeeting (request, id):
    form = None
    error = None
    try:
        meeting = Meeting.objects.get(id=id)
        if request.method == 'GET':
            form = MeetingUpdateForm(instance=meeting)
            form.fields['user_comitte'].queryset = User.objects.filter(pk__in=form.instance.user_comitte.all())
            form.fields['id_idea'].queryset = Idea.objects.filter(pk__in=form.instance.id_idea.all())

        else:
            form = MeetingUpdateForm(request.POST, instance=meeting)
            form_header = dict(request.POST.lists())
            
            if 'user_comitte' in form_header:
                collaborator_query = User.objects.filter(pk__in=form_header['user_comitte'])  #[1,2,3]
                form.fields['user_comitte'].queryset = collaborator_query

            if 'id_idea' in form_header:
                merge_idea_query = Idea.objects.filter(pk__in=form_header['id_idea'])
                form.fields['id_idea'].queryset = merge_idea_query

            if form.is_valid():	
                form.save()
                
            return HttpResponseRedirect(reverse('meeting:update',args=[id]))
    except ObjectDoesNotExist as e:
        error = e
        return render(request, '404.html', {'error':error})
  
    return render(request, 'meeting/update.html', 
    {'form': form,'error': error})


#Lista de actividades ---------------------------------------------------------------------------------
	
class watchMeeting(ListView,PermissionRequiredMixin):
	model = Meeting
	template_name = 'meeting/visualize_meeting.html'
	context_object_name = 'meeting'
	permission_required = 'meeting.view_meeting'

	def get_queryset(self):
			queryset = { 'meeting_all':Meeting.objects.all().prefetch_related('id_idea','user_comitte')}
						 # 'meeting_user':Comitte.objects.filter(user_is_active=True).prefetch_related('user_comitte')}
			return queryset 

# ------------------------------------------------------------------------------------------------------------------
"""Para crear el sistema de votación,consultamos las ideas que están agendadas en una reunión y que aún no se
han calificado en su última fase. Una vez ingresa el Usuario Comité puede votar una sola vez por cada idea, hasta
que la reunión este 'cerrada'"""

@login_required
@permission_required('meeting.view_meeting', raise_exception=True)

def registerComment(request,pk,id_idea):
	list_comments = []
	idea_query = Idea.objects.filter(
		uservotes__id_meeting=pk,
		uservotes__is_evaluate=False,
		uservotes__id_user_comitte=request.user.id, )
	is_voted=idea_query.count()
	
	for idea in idea_query:
     
		# Forma de traer la fase por consulta
		# consulta = Phase_Date.objects.prefetch_related('id_idea','id_phase').filter(id_idea_id=idea.id).values('id_phase_id').last()
		# idea_fases= consulta['id_phase_id']
  
		if idea.id == id_idea:
			list_comments.append({'id_meeting':pk,
							'id_idea':idea.id,
							'user':request.user.email,
       						})

	if request.method== 'POST':

		form=RegisterComment(request.POST)
		if form.is_valid():	
			UserVotes.objects.filter(
				id_meeting_id=pk,
				id_idea_id=request.POST.get("idea_input"),
				id_user_comitte=request.user.id,

			).update(is_evaluate=True,
					vote=form.cleaned_data['vote'],
					vote_priority=form.cleaned_data['vote_priority'],
					message=form.cleaned_data['message'],
					phase_actual=request.POST.get('id_idea_phase') )
		else:
			print("No es validooo")
		return HttpResponseRedirect(reverse('meeting:detail_meeting',args=[pk]))			
	else:
		form = RegisterComment()
	return render(request,'meeting/register_comment.html',
			{'form':form,'meetings_idea':list_comments, 'is_voted':is_voted, 'id_idea':id_idea})


# ----------------------------------------------------------------------------------------------------------------------------
"""Visualizar los detalles de la reunión, cargar el acta de reunión y
ver el estado de los votos por idea y cambia de fase si todos fueron aprobados"""

@login_required
@permission_required('meeting.view_meeting', raise_exception=True)

def comments_list(request, id_reu, id_idea):
	comentarios=UserVotes.objects.filter(id_meeting=id_reu,id_idea=id_idea)
	comentarios_total=UserVotes.objects.filter(id_meeting=id_reu,id_idea=id_idea).count()
	
	#fase
	next_fase=UserVotes.objects.filter(id_meeting=id_reu,id_idea=id_idea,vote=1).count()
	kepp_fase=UserVotes.objects.filter(id_meeting=id_reu,id_idea=id_idea,vote=2).count()
	die_idea=UserVotes.objects.filter(id_meeting=id_reu,id_idea=id_idea,vote=3).count()

	#prioridad
	priority_up=UserVotes.objects.filter(id_meeting=id_reu,id_idea=id_idea,vote_priority=1).count()
	priority_down=UserVotes.objects.filter(id_meeting=id_reu,id_idea=id_idea,vote_priority=2).count()
	kepp_priority=UserVotes.objects.filter(id_meeting=id_reu,id_idea=id_idea,vote_priority=3).count()
	print('kepp_priority',kepp_priority)

	none_idea= comentarios_total -(next_fase + kepp_fase + priority_up + priority_down+die_idea + kepp_priority) 

	# members=Meeting.objects.filter(user_comitte).count() 
	return render(request,'meeting/comments_list.html',{'comments_meetings_idea':comentarios, 'kepp_priority':kepp_priority,'next_fase':next_fase, 'kepp_fase':kepp_fase, 
	          'priority_up':priority_up, 'priority_down':priority_down, 'die_idea':die_idea, 'comentarios_total':comentarios_total,'none_idea':none_idea, 'id_idea':id_idea })

# Subir archivo -------------------------------------------------------------------------------------------------------------

@login_required
@permission_required('meeting.view_meeting', raise_exception=True)

def BasicUploadView(request,pk):
	path=Meeting.objects.get(id=pk)
	form = FileForm()
	if request.method == 'POST':
		form = FileForm(request.POST, request.FILES)  
		if form.is_valid():
			if 'document_act' in request.FILES:
				query=Meeting.objects.filter(id=pk,)
				for obj in query:
					obj.document_act=request.FILES['document_act']
					obj.save()
	else:
		form = FileForm()
	return render(request, 'meeting/upload.html', {'path': path,'form': form, 'pk':pk})

# ---Cards_detalle reunion	----------------------------------------------------

@login_required
@permission_required('meeting.view_meeting', raise_exception=True)

def detailMeeting(request,pk):
	meeting_query= Meeting.objects.filter(id=pk)

templates/meeting/close_meeting.html
{% load staticfiles %}

<div class="modal-dialog " role="document">
    <div class="modal-content">

        <div class="modal-header"><br>
            <h6 class=" "> ¿Estás seguro de finalizar esta reunión?</h6>
            <button class="close" type="button" data-dismiss = "modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">
           <div class="row">
            <div class="container">
              {% if request.user.is_authenticated %}
              <div class=" text-center">
                <form method="POST" action="{% url 'meeting:close' pk  %} ">{% csrf_token %}

                    <button type= "submit" class="btn btn-outline-danger mr-2"><i class="fas fa-trash-alt" style="color:red"></i> Si, cerrar</button>                    

                  <button type="button" class="btn btn-light" data-dismiss="modal">Volver</button>
                </form><br>
                <!-- <div class="card-footer text-muted">
                  <p class="text-muted"> ¡Ooops! Disculpa esta reunión ya se encuentra cerrada</p>
                    </div> -->
              </div>                      
            {% endif %}

             </div>
          </div>
      </div>
  </div>
</div>

templates/meeting/comments_list.html
{% load staticfiles %}

<style>

  .coments{
    height: 463px;
    overflow-y: scroll;
}

#disk_c{
 
  width: 100px;
  height: 80px;

  transform: rotate(270deg);
  margin: 20px 0px 13px -7px;
}

label{
  text-align: center;
  margin-bottom: 20px;
}

.votation{
  border-bottom: 1px solid #BBBABC;
  color: #818181;
}

.modal-content{
  border-radius: 25px;
}

.boxes{
  border-radius: 20px;
  padding: 10px;
  box-shadow: 0px 7px 18px 3px #f8f8f8;
  margin: 8px;
  border: 1px solid #f5f5f5;

}

.number{
  margin: 0;
  font-weight: 600;
}

meter::-webkit-meter-bar {
  background: #E6E5E5;
}

meter::-webkit-meter-optimum-value {background: #8C51A6;}

.message{
  margin: 12px;
  border-radius: 12px;
  padding: 9px;
  width: 92%;
  border: 1px solid #f5f5f5;
  box-shadow: 5px 5px 10px 5px rgb(234 234 234);

}

.avatar{
  width: 38px;
  border-radius: 50%;
  height: 38px;
  object-fit: cover;

}

.col-md-4{
  text-align: center;
}

.pub{
  border-bottom: 1px solid #BBBABC;
}

.title-c{
  margin: 4px;
  font-weight: 600;
}

.color-p{
  color: #8C51A6;
}

</style>


<div class="modal-dialog modal-dialog-centered modal-xl" role="document">
    <div class="modal-content">

          <div class="modal-header"><br>          
              <p class="title-c ">Resumen Comité <i class="fas fa-angle-right"></i> <span class="color-p">Idea {{id_idea}}</span></p>
              <!-- <h6 class="text-secondary">.text-secondary</h6>  -->
              <button class="close" type="button" data-dismiss = "modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>

          <div class="modal-body">
          <div class="row m-2">
            <div class="col-md-6">

              <div class="boxes">
                <p class="font-weight-bold pb-2 votation">Votación</p> 
                <span class="text-right">Número de participantes: </span> <span class="font-weight-bold ml-2"> {{comentarios_total}}</span>
                <div class="col-md-12 row">
             
                  <div class="col-md-4">
                    <meter id="disk_c" value="{{ kepp_fase }}" min="0" max="{{comentarios_total}}">{{ kepp_fase }}</meter>
                    <p class="number">{{ kepp_fase }}</p>
                    <p> Se mantiene en fase </p>
                  </div>

                  <div class="col-md-4">
                    <meter id="disk_c" value="{{ next_fase }}" min="0" max="{{comentarios_total}}"></meter>
                    <p class="text-center number">{{ next_fase }}</p>
                    <p>Avanza de fase </p>
                  </div>

                  <div class="col-md-4">
                    <meter id="disk_c" value="{{ die_idea }}" min="0" max="{{comentarios_total}}">{{ die_idea }}</meter>
                    <p class="text-center number">{{ die_idea }}</p>
                    <p>Enviar a Banco de Ideas</p>
                  </div>


                  <div class="col-md-4">
                    <meter id="disk_c" value="{{ kepp_priority }}" min="0" max="{{comentarios_total}}">{{ kepp_priority }}</meter>
                    <p class="text-center number">{{ kepp_priority }}</p>
                    <p>Se mantiene en prioridad </p>
                  </div>
                  
                  <div class="col-md-4">
                    <meter id="disk_c" value="{{ priority_up }}" min="0" max="{{comentarios_total}}">{{ priority_up }}</meter>
                    <p class="text-center number">{{ priority_up }}</p>
                    <p>Sube prioridad </p>
                  </div>
  
                  <div class="col-md-4">
                    <meter id="disk_c" value="{{ priority_down }}" min="0" max="{{comentarios_total}}">{{ priority_down }}</meter>
                    <p class="text-center number">{{ priority_down }}</p>
                    <p>Baja de prioridad </p>
                  </div>
  
                  
  
                  
  
                  
                  <div class="col-md-4">
                    <meter id="disk_c" value="{{ none_idea }}" min="0" max="{{comentarios_total}}"></meter>
                    <p class="text-center number">{{ none_idea }}</p>
                    <p>Sin responder </p>
                  </div>
                </div>
  
              </div>
             

            </div>

            <div class="col-md-6 ">
              <div class="boxes coments">
                <p class="font-weight-bold pb-2 votation">Comentarios</p> 

                {% for lista in comments_meetings_idea%}
  
                <div class="col-md-12 row  message">
                  <div class="col-md-2">
                    <img src="{{lista.id_user_comitte.profile.avatar.url}}" class="avatar" data-toggle="tooltip" data-placement="top"  >  
                  </div>
                  <div class="col-md-10">
                    <a href="#">{{lista.id_user_comitte}}</a>
                    <p class="text-muted pub">{{lista.pub_date}}</p> 
                    <p>{{lista.message|safe|default_if_none:"Por responder" }} </p>
                    <p> Voto Fase: <b>{{lista.get_vote_display}}</b> </p>
                    <p> Voto Prioridad: <b>{{lista.get_vote_priority_display}}</b> </p>
                  </div>
                </div>
  
              {% endfor %}
              </div>

            
            </div>
            
          </div>

          </div>

      </div>
    </div>
       
        



     
            

templates/meeting/upload.html
{% extends 'base_template_admin.html' %}
{% load staticfiles %}
{% block titulo %}Verne | Upload {% endblock titulo %}

{% block body_content %}
<div class="content-wrapper">
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'meeting:visualize' %}">Lista de Ideas</a></li>
              <li class="breadcrumb-item active"> Subir Archivo </li>
            </ol>
          </div>
        </div>
      </div>
    </section>
    <style type="text/css">

      .nube{
          font-size:110px;color:#00ada1;
        }
    </style>
    <section class="content">
     <div class="container">  
        <div class="col-md-10 ">
            <h4 class=" col-md-8 container ">Adjuntar archivo</h4>
             <div class="card-body">
               <form enctype="multipart/form-data"  method="post" class="form-row"> {% csrf_token %} 
                 <div class="col-md-12 text-center">
                   
                  <div class="col-md-8 container card border border-info">                 
                    <p class="mt-3">Selecciona un archivo</p>
                     <i class=" nube fas fa-cloud-upload-alt "></i>
                     <div class="upload mt-3 mb-3">
                      {{ form.document_act}}
                    </div> 
                  </div>
                  <div class="card col-md-6 container  mb-4">
                    <div class="card-header text-muted"> Archivos subidos anteriormente </div>
                    <div class="card-body">
                    {% if path.document_act %}
                    <a href="{{ path.document_act.url }}">{{ path.document_act.url }}</a>
                    {% else %}
                    <p>Aún no se han subido archivos </p>
                    {% endif %}
                    </div>
                  </div>
                <button class="btn btn-info rounded-pill "type="submit" value="Save">Enviar Archivo</button>
                 <a class="btn btn-outline-secondary rounded-pill" href="{% url 'meeting:detail_meeting' pk %}" > Regresar </a>
                </div>
           </form>         
         </div>
       </div>
     </div>
    </section>
</div>
{% endblock body_content %}