apps/idea/urls.py
from django.urls import path
from .views import *
from .view_ajax import *


urlpatterns = [

	#Vistas de Ideas
	path('register/', registerIdea.as_view(), name='register'),
	path('evaluate/',watchIdea.as_view(), name='evaluate'),
 	path('search_colaborator/',SearchColaborator.as_view(), name='search_colaborator'),
    path('search_subregion/',SearchSubregion.as_view(), name='search_subregion'),
 
 
	path('evaluate/<int:fase>/',watchIdeaPhase.as_view(), name='phase_list'),
	path('bank_idea/', IdeaBank.as_view(), name='bank'),
	path('evaluate/update/<int:id>', UpdateIdea, name='update'),
    #path('evaluate/updates/<int:id>', idea_de_prueba.as_view(), name='updates'),
    path('dashboard_innovation/', visualizeDashboardAjax.as_view(), name='general_dashboard'),
  	path('dashboard/ideas_details/<int:id_idea>/', detailsIdeaDashboard, name='idea_details'),
	path('phases/<int:id>/<int:fase>/', PhaseDocumentation, name='phase_documentation'),
	path('evaluate/record/<int:id_idea>', RecordIdea, name='record'),
    path('evaluate/review/<int:id_idea>', revisar_idea, name='review'),
    path('evaluate/revisar_idea_externa', revisar_idea_externa, name='revisar_idea_externa'),


	#Para el Loader more en dashboard y Ideas en Stand By
	path('posts-json/<int:num_posts>/<int:fase>/', EncabezadoDetalleNosotrosJsonListView.as_view(), name='posts-json-view'),

	#Busqueda por AJAX de idea y usuario
	path('buscar_merge/', SearchAjaxIdea.as_view(), name='buscar_merge'),
	path('buscar_colaborador/', SearchUserAjax.as_view(), name='buscar_colaborador'),
	path('buscar_id_idea/', SearchAjaxIdIdeaFilters.as_view(), name='buscar_id_idea'),
    path('buscar_frente/', SearchAjaxIdFrenteFilters.as_view(), name='buscar_frente'),

 	#Lista de externas ideas
 	path('external_idea/',ExternalIdeaList.as_view(), name='external_idea'),
 	path('external_idea_state/<int:pk>',ExternalIdeaState, name='external_idea_state'),
    
	path('aceptar_idea_externa/',aceptar_idea_externa, name='aceptar_idea_externa'),
    path('rechazar_idea_externa/',rechazar_idea_externa, name='rechazar_idea_externa'),
 	
	path('external_idea_state_aproved/<int:pk>',ExternalIdeaStateAproved, name='external_idea_state_aproved'),
 	path('external_idea_state_reached/<int:pk>',ExternalIdeaStateReached, name='external_idea_state_reached'),


	#Lista de opciones de Editar Idea
	path('evaluate/update/inactive/<int:pk>', inactive_idea, name='inactive'),
	path('evaluate/update/question_pain/<int:pk>', QuestionPain, name='question'),
	path('evaluate/update/change_phase/<int:pk>', changePhase.as_view(), name='change'),
	path('evaluate/update/restore/<int:pk>', reactive_idea, name='restore'),
	path('evaluate/update/upload/<int:pk>',BasicUploadView, name='upload'),
	path('evaluate/update/fastrack/<int:pk>', fastrackIdea, name='fastrack'),

	#Task List con AJAX por fase
	path('list_task/',ListTask.as_view(), {'parametro_extra':"Listado Proyecto"}, name='list_task'), 
	path('task_create/', CreateTask.as_view(), name = 'task_create'),
	path('task_update/<int:pk>/', EditTask.as_view(), name='task_update'),
	path('task_delete/<int:pk>/', DeleteTask.as_view(), name='task_delete'),

	#Generar pdf
	path('ticket/<int:pk>/', IdeaGeneratorPdf.as_view(), name='ticket'),

	#Task List con AJAX por idea
	path('list_task_idea/',ListTaskIdea.as_view(), {'parametro_extra':"Listado Proyecto"}, name='list_task_idea'), 
	path('task_create_idea/', CreateTaskIdea.as_view(), name = 'task_create_idea'),
	path('task_update_idea/<int:pk>/', EditTaskIdea.as_view(), name='task_update_idea'),
	path('task_delete_idea/<int:pk>/', DeleteTaskIdea.as_view(), name='task_delete_idea'),

	#Visualizar imagenes y archivos
	
]

verne2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from apps.idea.views import visualizeDashboardUser
from django.views.generic import TemplateView
from apps.home.views import *


#Modulos del API
from rest_framework import routers
from apps.idea.api.api_rest import UserViewSet,IdeaViewSet,PhaseViewSet
from apps.meeting.api.api_rest import MeetingViewSet,UserVotesgViewSet
from apps.activity.api.api_rest import ActivityViewSet
from apps.prize.api.api_rest import PrizeViewSet,ActionViewSet,LeguasViewSet
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Documentación API')
router = routers.DefaultRouter()
router.register(r'usuario', UserViewSet, basename='usuario')
router.register(r'idea', IdeaViewSet, basename='idea')
router.register(r'reunion', MeetingViewSet, basename='reunion')
router.register(r'votacion', UserVotesgViewSet, basename='votacion')
router.register(r'actividad', ActivityViewSet, basename='actividad')
router.register(r'premios', PrizeViewSet, basename='premios')
router.register(r'acciones', ActionViewSet, basename='acciones')
router.register(r'leguas', LeguasViewSet, basename='leguas')
router.register(r'fases', PhaseViewSet, basename='fases')


urlpatterns = [
	path('admin/', admin.site.urls, name = 'admin_django'),

	#API
    path('api/v1/', include(router.urls)),
    path(r'documentacion/', schema_view), #Documentación Principal 

    #Autenticación Google
    #path('accounts/', include('allauth.urls')), # new

	#Autenticación Google
    path("login", login_request, name="login"),
    path("logout", logout_request, name= "logout"),
    path('microsoft/', include('microsoft_auth.urls', namespace='microsoft')),
	#Llamado a las apps para crear la ruta
	path('ideas/',include(('apps.idea.urls','idea'))),
	path('meeting/',include(('apps.meeting.urls','meeting'))),
	path('prize/',include(('apps.prize.urls','prize'))),
	path('activity/',include(('apps.activity.urls','activity'))),
	path('dashboard/', visualizeDashboardUser, name='dashboard'),
	path('users/',include(('apps.users.urls','users'))),
	path('indicador/',include(('apps.indicators.urls','indicator'))),

	#URL Landing Page
	path('', ViewHome, name='home'),
	path('sign_in', LoginPage, name='singin'),

    #Manejo de errores
	path('404/', TemplateView.as_view(template_name="404.html")),
    path('500/', TemplateView.as_view(template_name="500.html")),
    path('403/', TemplateView.as_view(template_name="403.html")),
  	path('ckeditor/', include('ckeditor_uploader.urls')),

]
 

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	import debug_toolbar
	urlpatterns = [
		path('__debug__/', include(debug_toolbar.urls)),
	] + urlpatterns    

admin.site.site_header = "Administrador de Verne 2.0"
admin.site.site_title = "Administración de Verne 2.0"
admin.site.index_title = "Administración de Verne 2.0"

apps/idea/models.py
from unicodedata import name
from unittest.mock import DEFAULT
from urllib import request
from django.db import models
from simple_history.models import HistoricalRecords
from django.contrib.auth.models import User
from django.db.models.fields import URLField
from apps.users.models import Profile


# Para el disparador que asigna automáticamente al grupo Users
#------------------------------------------
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import Group

@receiver(models.signals.post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		instance.groups.add(Group.objects.get(name='Users'))
		instance.save()		   
#------------------------------------------


STATES=(
	("Aprobado","Aprobado"),
	("Rechazado","Rechazado"),
	("En revisión","En revisión"),
	("Por definir","Por definir"),)

PROPOSITOS=(
	("Sí","Sí"),
	("No","No"),)

class Area(models.Model):
	nombre=models.CharField(max_length=300,verbose_name=u'Descripción')
	history = HistoricalRecords()

	def __str__(self):
		return self.nombre
	
	class Meta:
		verbose_name = "Area"
		verbose_name_plural = "Areas"


class Beneficio(models.Model):
	nombre=models.CharField(max_length=300,verbose_name=u'Descripción')
	history = HistoricalRecords()

	def __str__(self):
		return self.nombre
	
	class Meta:
		verbose_name = "Beneficio"
		verbose_name_plural = "Beneficios"


class Frente(models.Model):
	nombre=models.CharField(max_length=300,verbose_name=u'Descripción')
	history = HistoricalRecords()

	def __str__(self):
		return self.nombre
	
	class Meta:
		verbose_name = "Frente"
		verbose_name_plural = "Frentes"

class Dimension(models.Model):
	nombre=models.CharField(max_length=300,verbose_name=u'Descripción')
	history = HistoricalRecords()

	def __str__(self):
		return self.nombre
	
	class Meta:
		verbose_name = "Dimension"
		verbose_name_plural = "Dimensiones"


class Objective(models.Model):
	nombre=models.CharField(max_length=300,verbose_name=u'Descripción')
	year=models.IntegerField(verbose_name=u'Año')
	history = HistoricalRecords()

	def __str__(self):
		return self.nombre
	
	class Meta:
		verbose_name = "Objectivo"
		verbose_name_plural = "Objectivos"

 
class ExternalIdea(models.Model):
	creation_date=models.DateField(auto_now_add=True,verbose_name=u'Fecha de creación')#auto_now_add=True,
	description=models.TextField('Descripción',max_length=5000)
	solucion=models.TextField('Solución',max_length=5000)
	title=models.CharField('Título',max_length=150)
	state=models.CharField(max_length=20, choices=STATES, default="Por definir", blank=True,null=True,verbose_name=u'Estado')
	proposito=models.CharField(max_length=20, choices=PROPOSITOS, default="Sí", blank=True,null=True,verbose_name=u'Proposito')
	external_name = models.CharField('Nombre externo',max_length=150)
	external_email= models.CharField('Email externo',max_length=150)
	conditions=models.BooleanField(default=True,verbose_name=u'Términos y condiciones' ,null=False, blank=False)
	feedback=models.TextField('Comentarios',max_length=5000, default=" ")
	gerencia=models.ForeignKey(Area,on_delete=models.CASCADE, verbose_name=u'Gerencia', blank=True,null=True)
	subregion = models.ForeignKey(Beneficio,on_delete=models.CASCADE,verbose_name=u'Subregión', blank=True,null=True)
	frente=models.ForeignKey(Frente,on_delete=models.CASCADE,verbose_name=u'Frente', blank=True,null=True)
	dimension = models.ForeignKey(Dimension,on_delete=models.CASCADE,verbose_name=u'Dimensión', blank=True,null=True)
	pilar = models.ForeignKey(Objective,on_delete=models.CASCADE,verbose_name=u'Objetivos', blank=True,null=True)
	documento=models.IntegerField(verbose_name=u'Cedula', default=0, blank=True,null=True)
	revision=models.TextField('Revision del problema',max_length=5000, blank=True,null=True)

	#Add more fields here
 
	class Meta:
		verbose_name = "Ideas Externas"
		verbose_name_plural = "Ideas Externas"
  
  
class PriceScore (models.Model):
	price=models.IntegerField(verbose_name=u'Valor Legua', default=0)

	class Meta:
		verbose_name = "Valor Legua"
		verbose_name_plural = "Valor Legua"





class QuestionPhase(models.Model):
	name=models.CharField(null=False ,blank=False, max_length=200,verbose_name=u'Pregunta')
	date=models.DateField(null=True,auto_now_add=True,verbose_name=u'Fecha')
	history = HistoricalRecords()

	def __str__(self):
		return self.name
	
	class Meta:
		verbose_name = "Pregunta Pain"
		verbose_name_plural = "Preguntas Pain"


class Phase(models.Model):
	name=models.CharField(max_length=50,verbose_name=u'Nombre Fase')
	history = HistoricalRecords()

	def __str__(self):
		return self.name
	
	class Meta:
		verbose_name = "Fase"
		verbose_name_plural = "Fases"


class Task(models.Model):

	STATES=(
	("Por hacer","Por hacer"),
	("En ejecución","En ejecución"),
	("Completado","Completado"),)


	
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,verbose_name=u'Encargado')
	title = models.CharField(max_length=200,verbose_name=u'Título')
	description = models.TextField(null=True, blank=True,verbose_name=u'Notas')
	complete = models.BooleanField(default=False,verbose_name=u'Estado')
	created = models.DateTimeField(auto_now_add=True,verbose_name=u'Fecha creación')

	def __str__(self):
		return self.title

	class Meta:
		order_with_respect_to = 'user'
		verbose_name = "Tareas por fase"
		verbose_name_plural = "Tareas por fase"


class TaskByIdea(models.Model):

	STATES=(
	("Por hacer","Por hacer"),
	("En ejecución","En ejecución"),
	("Completado","Completado"),)
	user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='UsersIdea', null=True, blank=True,verbose_name=u'Encargado')
	title = models.CharField(max_length=200,verbose_name=u'Título')
	description = models.TextField(null=True, blank=True,verbose_name=u'Notas')
	#complete = models.BooleanField(default=False,verbose_name=u'Estado')
	complete=models.CharField(max_length=20, choices=STATES, default="Por hacer", blank=True,null=True,verbose_name=u'Estado')

	created = models.DateTimeField(auto_now_add=True,verbose_name=u'Fecha creación')

	def __str__(self):
		return self.title

	class Meta:
		order_with_respect_to = 'user'
		verbose_name = "Tareas por Idea"
		verbose_name_plural = "Tareas por Idea"


class Idea(models.Model):

	INNOVATION_TYPE=(
		("Incremental","Incremental"),
		("Producto","Producto"),
		("Procesos","Procesos"))

	INNOVATION_PRIORITY=(
		("ALTA","Alta"),
		("MEDIA","Media"),
		("BAJA","Baja"),)
	
	INNOVATION_ESTRATEGIA=(
		("Crecimiento de mercados","Crecimiento de mercados"),
		("Innovación","Innovación"),
		("Sostenibilidad","Sostenibilidad"),
		("Nuestra gente y cultura","Nuestra gente y cultura"),
		("Productividad y mejora continua","Productividad y mejora continua"),)
	

	def custom_upload_to_documento(instance, filename):
		old_instance = Idea.objects.get(pk=instance.pk)
		old_instance.primer_documento.delete()
		return 'home/' + filename
	
	def custom_upload_to_documento2(instance, filename):
		old_instance = Idea.objects.get(pk=instance.pk)
		old_instance.segundo_documento.delete()
		return 'home/' + filename
	
	def custom_upload_to_documento3(instance, filename):
		old_instance = Idea.objects.get(pk=instance.pk)
		old_instance.tercer_documento.delete()
		return 'home/' + filename

	creation_date=models.DateField(auto_now_add=True,verbose_name=u'Fecha de creación')#auto_now_add=True,
	description=models.TextField('Descripción de problema',max_length=5000, blank=True,null=True)
	title=models.CharField('Título',max_length=150, blank=True,null=True)
	is_active=models.BooleanField(default=True,verbose_name=u'¿Está activa?')
	priority=models.CharField(max_length=20, choices=INNOVATION_PRIORITY, blank=True,null=True,verbose_name=u'Prioridad')
	innovation_type=models.CharField(max_length=20, choices=INNOVATION_TYPE, blank=True,null=True,verbose_name=u'¿En qué etapa se encuentra ia idea?')
	
	innovation_estrategia=models.CharField(max_length=40, choices=INNOVATION_ESTRATEGIA, blank=True,null=True,verbose_name=u'¿A que pilar estratégico le apunta la idea?')
	
	is_merge=models.BooleanField(default=False,verbose_name=u'¿Es merge?',blank=True,null=True)
	is_fastrack=models.BooleanField(default=False,verbose_name=u'¿Es fastrack?',blank=True,null=True)
	current_phase=models.IntegerField(null=True, blank=True,verbose_name=u'Fase Actual')
	conditions=models.BooleanField(default=True,verbose_name=u'Términos y condiciones' , blank=True,null=True)
	link_documentation=URLField(max_length=1500, verbose_name=u'Enlace a Documentación', null = True, blank=True, default=" https://drive.google.com/")
	descripcion_beneficio=models.TextField('Describe el beneficio',max_length=5000, default=' ',null=True, blank=True)
	asigned=models.ForeignKey(User,on_delete=models.CASCADE,related_name="asigned",verbose_name=u'Encargado', default="", null=True, blank=True)

	gain=models.FloatField(verbose_name=u'Beneficio',null=True, blank=True, default=0)
	investment =models.FloatField(verbose_name=u'Inversión adicional',null=True, blank=True, default=0)
	roi =models.FloatField(verbose_name=u'ROI',null=True, blank=True, default=0)
	score_idea=models.IntegerField(null=True, blank=True,verbose_name=u'Leguas invertidas',default=0)
	price_score=models.IntegerField(null=True, blank=True,verbose_name=u'Precio total leguas',default=0)
	total_investment = models.FloatField(verbose_name=u'Inversión total',null=True, blank=True, default=0)

	id_merge=models.ManyToManyField('self',  blank=True, related_name='evaluations')	# Para el merge entre dos ideas la tabla idea se autollama
	state=models.CharField(max_length=20, choices=STATES, default="Sí", blank=True,null=True,verbose_name=u'Proposito')


	id_question=models.ManyToManyField(QuestionPhase, through='IdeaQuestionPhase',
		through_fields=('id_idea', 'id_question'),)
	id_phase=models.ManyToManyField(Phase, through='Phase_Date',
		through_fields=('id_idea', 'id_phase'),default=1)

templates/idea/dashboard_ajax.html
{% extends 'base_template_admin.html' %}
{% load staticfiles %}
{% block titulo %}Verne | Dashboard {% endblock titulo %}
{% load humanize %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'dist/css/verne/idea/dashboard_styles.css' %}">

  <!-- BEGIN: Bootstrap Date-Picker Range Plugin -->
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<!-- END: Bootstrap Date-Picker Range Plugin -->
<link href="{% static 'vendor/select2/dist/css/select2.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

{% endblock extra_css %}

{% block body_content %}
<!-- spiner loader -->
<div class="col-12 text-center" id='loader' style='display: none;'>
  <div class='overlay custom-loader-background'>
      <i class='fa fa-cog fa-spin custom-loader-color'></i>
  </div>
</div>
<!-- spiner loader -->

<div class="wrapper"  >
  <div class="content-wrapper" >
    <section class="content-header">
      <div class="container-fluid">
      	<p class="dasboard-title ml-4 mb-0 row">Dashboard

  
          <button class="btn btn-secondary mr-5 rounded-pill text-right ml-auto" type="button" data-toggle="collapse" data-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2"><i class="fas fa-filter pr-1"></i>Filtros</button>
        </p>
      
        <div class="collapse multi-collapse" id="multiCollapseExample1">
    
            <div class="card-body ml-4 mr-5">
              <form action="{% url 'idea:general_dashboard' %}" method="GET" class="form-horizontal">  
              <div class="row">
                
                <div class="col-12 col-lg-2 col-sm-2">
                  <div class="form-group">
                      {{ form.id_idea.label }}
                      {{ form.id_idea }}
                  </div>
                </div>

                  <div class="col-12 col-lg-3 col-sm-3">
                    <div class="form-group">
                        {{ form.titulo.label }}
                        {{ form.titulo }}
                    </div>
                  </div>
        
                  <div class="col-12  col-lg-3 col-sm-3">
                    <div class="form-group">
                        {{ form.tipo_innovacion.label }}
                        {{ form.tipo_innovacion }}
                    </div>
                  </div>
        
                  <div class="col-12  col-lg-3 col-sm-3">
                    <div class="form-group">
                        {{ form.prioridad.label }}
                        {{ form.prioridad }}
                    </div>
                  </div>
        
                  <div class="col-12 col-xl-3 col-lg-6 col-sm-6">
                    <div class="form-group">
                        {{ form.datarange.label }}
                        {{ form.datarange }}
                          <div class="error_message" id="{{ form.datarange.id_for_label }}"> {{ form.datarange.error}} </div>
        
                    </div>
                  </div>

                  <!-- Autores -->
                  <div class="col-12 col-xl-5 col-lg-6 col-sm-6">
                    <div class="form-group">
                     {{form.collaborator.label}}
                      {{form.collaborator}}
                    </div>
                  </div>

                  <!-- Frentes 
                  <div class="col-12 col-xl-5 col-lg-6 col-sm-6">
                    <div class="form-group">
                     {{form.frente.label}}
                      {{form.frente}}
                    </div>
                  </div>-->
        
                  <div class="col-3 col-xl-1 col-lg-1 col-sm-2">
                    <div class="form-group">
                      <label for=""> </label>
                    <button class="btn btn-secondary rounded-pill btn-block" type="submit">
                      <i class="fa fa-search"></i>
                    </button>
                    <!-- 
                      enviar un localstorage
                     <button class="btn btn-secondary rounded-pill btn-block" onclick="storeid()">
                      <i class="fa fa-search"></i>
                    </button>
                     -->
                    </div>
                  </div>
                
              </div>
            </form>
            </div>
    
        </div>

      </div>
    </section>

 
  
  {% if perms.idea.add_idea %}  
	<section class="content ml-4 mr-4 mt-0" >
	  <div class="container-fluid row " >

    {% for phase in phases %}
      {% if phase.id == 1 %}
 	 <!-- -----Fase Pain ------------------------------- -->
        <div class="col-lg-3 col-sm-6 col-xs-12" >
        	<a href="{% url 'idea:phase_list' 1 %}">
              <div class="inner phase-one">
                <span> <i class="fas fa-bolt icon phase1 ml-2"></i></span>
                <span class="phase1 ml-2">{{phase.name}}</span>
                <span id="count_pain" class="badge badge-pill badge-pain ml-2"></span>
                <span class="expand"><i class="fas fa-expand-arrows-alt	"></i>  </span>
              </div> 
        	</a>
               
			<div class="courses-container" id="posts-box"></div>
			  
			<div class="text-center pb-1" id="loading-box">
				<button class=" btn badge-pain loader-more" id="load-btn">Cargar más</button>
				<div id="spinner-box" class="not-visible">
				  <div class="spinner-border text-primary" role="status"></div>
				</div>
			</div>
        
        </div>

		<!-- --------Fase Observacion---------------------------->
    {% elif phase.id == 2 %}
        <div class="col-lg-3 col-sm-6 col-xs-12" >
        	<a href="{% url 'idea:phase_list' 2 %}">
              <div class="inner phase-two">
                <span> <i class="fas fa-search icon phase2 ml-2"></i></span>
                <span class="phase2 ml-2">{{phase.name}}</span>
                <span id="count_obs" class="badge badge-pill badge-obs ml-2"></span> 
                <span class="expand"><i class="fas fa-expand-arrows-alt	"></i>  </span>
    
            </div> 
        	</a>

			<div class="courses-container" id="posts-box-obs"></div>
			  
			<div class="text-center pb-1" id="loading-box-obs">
				<button class=" btn loader-more badge-obs" id="load-btn-obs">Cargar más</button>
				<div id="spinner-box-obs" class="not-visible">
				  <div class="spinner-border text-primary" role="status"></div>
				</div>
			</div>          	        
        </div>

		<!-- Fase Ideacion ----------------------------------------- -->
    {% elif phase.id == 3 %}
     <div class="col-lg-3 col-sm-6 col-xs-12 ">
		<a href="{% url 'idea:phase_list' 3 %}">
          <div class="inner phase-three">
            <span> <i class="fas fa-lightbulb icon phase3 ml-2"></i></span>
            <span class="phase3 ml-2">{{phase.name}}</span>
            <span id="count_ide" class="badge badge-pill badge-ids ml-2"></span>       
            <span class="expand"><i class="fas fa-expand-arrows-alt"></i>  </span>   
          </div> 
    	</a>
		<div class="courses-container" id="posts-box-ide"></div>

		<div class="text-center pb-1" id="loading-box-ide">
			<button class=" btn loader-more badge-ids" id="load-btn-ide">Cargar más</button>
			<div id="spinner-box-ide" class="not-visible">
			  <div class="spinner-border text-primary" role="status"></div>
			</div>
		</div>  	        
    </div>

		<!-- Fase prototipado ------------------------------------- -->
    {% elif phase.id == 4 %}
       <div class="col-lg-3 col-sm-6 col-xs-12 ">
       	<a href="{% url 'idea:phase_list' 4 %}">
          <div class="inner phase-four">
            <span> <i class="fas fa-chart-pie icon phase4 ml-2"></i></span>
            <span class="phase4 ml-2">{{phase.name}}</span>
            <span id="count_pro" class="badge badge-pill badge-pro ml-2"></span>
            <span class="expand"><i class="fas fa-expand-arrows-alt"></i>  </span>    
          </div> 
    	</a>       
		<div class="courses-container" id="posts-box-pro"></div>

		<div class="text-center pb-1" id="loading-box-pro">
			<button class=" btn loader-more badge-pro" id="load-btn-pro">Cargar más</button>
			<div id="spinner-box-pro" class="not-visible">
			  <div class="spinner-border text-primary" role="status"></div>
			</div>
		</div>        
    	</div>

      {% endif %}
      {% endfor %}

    </section>

  {% endif %}

	</div>
</div>


<div class="modal fade" id="ModalDetail" role="dialog"></div>


<div class="modal fade" id="ModalInactive" role="dialog"></div>
<div class="modal fade" id="ModalPhase" role="dialog"></div>
<div class="modal fade" id="ModalReference" role="dialog"></div>
<div class="modal fade" id="ModalReactive" role="dialog"></div>
<div class="modal fade" id="ModalFastrack" role="dialog"></div>
<div class="modal fade" id="creacion" role="dialog"></div>

<!-- Editar Regla -->
<div class="modal fade" id="edicion" role="dialog"></div>

<!-- eliminacion Regla -->
<div class="modal fade" id="eliminacion" role="dialog"></div>


{% endblock body_content %}

{% block extra_js %}

<!-- BEGIN: Bootstrap Date-Picker range Plugin -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<!-- BEGIN: Bootstrap Date-Picker range Plugin -->

<script src="{% static 'vendor/select2/dist/js/select2.full.js' %}" crossorigin="anonymous"></script>

<!-- Include Bootstrap Datepicker -->
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

<!-- BEGIN: JS Personalizado de AJAX -->
<script src="{% static 'dist/js/verne/idea/dashboard.js' %}"></script>
<!-- END:  JS Personalizado  de AJAX  -->

<script src="{% static 'dist/js/verne/idea/modals_idea.js' %}"></script>


{% endblock extra_js %}